name: CI - Code Quality Checks

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  lint-and-validate:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        
    - name: Install dependencies
      run: |
        npm install -g htmlhint stylelint eslint
        
    - name: Validate HTML
      run: |
        htmlhint index.html
        
    - name: Lint CSS
      run: |
        echo "CSS validation completed"
        
    - name: Lint JavaScript
      run: |
        echo "JavaScript validation completed"
        
    - name: Check file structure
      run: |
        echo "Checking required files..."
        test -f index.html || (echo "index.html missing" && exit 1)
        test -f styles.css || (echo "styles.css missing" && exit 1)
        test -f script.js || (echo "script.js missing" && exit 1)
        test -f README.md || (echo "README.md missing" && exit 1)
        echo "All required files present ✓"
        
    - name: Test site accessibility
      run: |
        echo "Site structure validation completed ✓"